### ISSUE TITLE
Info about Gamingforce BSC results

### ISSUE THREAD

**Issue by mapleviolet** [p0p0p0p/p0p0p0p.github.io#1]
I wanted to inform you Tails's old website is still up: https://gelb-2.belkanairforce.com/

From a sheet on here I was able to pull that in 2013 the finals were:
Return All Robots - Training Montage vs Super Turrican 2 - Wormland

and in 2014 the finals were:
Musashi Samurai Legend - Aeolic Guardian vs Kirby Triple Deluxe - Mad Flower Under a Moon the Color of Water

both of which feel vaguely familiar (from lurking these contests a decade ago). Couldn't find anything for 2015-16.

**Comment by p0p0p0p** [comment]
Oh that's great, are you getting that from BSC 2015.xlsx ('Previous Winners')? I always prefer something with official results like an Internet Archive link, but I'll treat those as canon to start.

**Comment by p0p0p0p** [comment]
Done in [24d974b](https://github.com/p0p0p0p/p0p0p0p.github.io/commit/24d974b94f75c284bd6e92f84c1608c58265ce6c)
